### ISSUE TITLE
API Error: Objective and Strategic Objectives

### ISSUE THREAD

**Issue by crajapax** [toladata/TolaDataV2#47]
Running a Test to post Data to the APIs and getting Error Messages for 
the APIs: "objective": "http://activity.toladata.io/api/objective/" and
 "strategicobjective": "http://activity.toladata.io/api/strategicobjective/".  It is not possible to post data with the "post" requests. A "Server Error"  (<Response [500]>) message is returned.

**Comment by glind** [comment]
These happen in version 1 of the API on the TolaData.io server so we should check in both branches.
